package sql

import (
	"github.com/staumann/caluclation/model"
	"log"
)

// SaveUser stores the given userData in the database. The id of the user is generated by the database and added to the user
// object after storage
func (a *Adapter) SaveUser(user *model.User) error {
	res, err := a.db.Exec(a.getScript("insert/user"), user.Name)

	if err != nil {
		log.Printf("error saving user: %s", err.Error())
		return err
	}

	user.ID, _ = res.LastInsertId()

	return nil
}

// GetUserById returns the user associated with the given id
func (a *Adapter) GetUserByID(id int64) *model.User {
	user := new(model.User)
	err := a.db.QueryRow(a.getScript("/get/user"), id).Scan(&user.ID, &user.Name)

	if err != nil {
		log.Printf("error getting unser: %s", err.Error())
		return nil
	}

	return user
}
